apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vidar-sandbox-service
  name: vidar-sandbox-service-deployment
spec:
  selector:
    matchLabels:
      app: vidar-sandbox-service
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: vidar-sandbox-service
    spec:
      containers:
        - name: vidar-sandbox-service
          image: vidar-sandbox
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
        - name: quarkus-jvm-sidecar
          image: quarkus/vidar-quarkus-request-intercept-jvm
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: vidar-sandbox-service-k8svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: vidar-sandbox-service
  type: LoadBalancer
  externalIPs:
    - 192.168.64.2

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  labels:
#    service: vidar-sandbox-service
#  name: vidar-sandbox-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: vidar-sandbox-service
#                port:
#                  number: 8082